# weeklybudget_generator.py
"""
Module to create next week's budget document based on previous week's maxBudgetPaise.
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pymongo import MongoClient
from datetime import datetime, timedelta

MONGO_URI = "mongodb+srv://mumbaihacks:mumbaihacks@cluster0.fonvcex.mongodb.net/"
DB_NAME = "test"

def get_week_dates(date=None):
    """Get the start and end dates for a week (Monday to Sunday)"""
    if date is None:
        date = datetime.now()
    
    start_of_week = date - timedelta(days=date.weekday())
    start_of_week = start_of_week.replace(hour=0, minute=0, second=0, microsecond=0)
    
    end_of_week = start_of_week + timedelta(days=6)
    end_of_week = end_of_week.replace(hour=23, minute=59, second=59, microsecond=999999)
    
    first_day_of_year = datetime(date.year, 1, 1)
    days_since_year_start = (start_of_week - first_day_of_year).days
    week_number = (days_since_year_start + first_day_of_year.weekday() + 1) // 7 + 1
    
    return {
        'weekStartDate': start_of_week,
        'weekEndDate': end_of_week,
        'weekNumber': week_number,
        'year': date.year
    }


def create_next_week_budget(user_id: str):
    """
    Creates next week's budget document based on previous week's maxBudgetPaise.
    All spending fields are reset to 0, budgets are copied from previous week.
    """
    
    try:
        # Connect to MongoDB
        client = MongoClient(MONGO_URI)
        db = client[DB_NAME]
        weekly_budgets = db.weeklybudgets
        
        # Get next week's dates
        next_week_date = datetime.now() + timedelta(days=7)
        next_week = get_week_dates(next_week_date)
        
        # Check if next week's budget already exists
        existing_budget = weekly_budgets.find_one({
            "userId": user_id,
            "weekNumber": next_week['weekNumber'],
            "year": next_week['year']
        })
        
        if existing_budget:
            return {
                "success": False,
                "error": f"Budget already exists for week {next_week['weekNumber']}, {next_week['year']}",
                "existingDocument": {
                    "_id": str(existing_budget['_id']),
                    "weekNumber": existing_budget['weekNumber'],
                    "year": existing_budget['year']
                }
            }
        
        # Get current week's budget to copy maxBudgetPaise values
        current_week = get_week_dates()
        current_budget = weekly_budgets.find_one({
            "userId": user_id,
            "weekNumber": current_week['weekNumber'],
            "year": current_week['year']
        })
        
        if not current_budget:
            return {
                "success": False,
                "error": f"No current week budget found for user {user_id}. Cannot create next week's budget.",
                "userId": user_id
            }
        
        # Create new budget document with reset values
        new_budget = {
            "userId": user_id,
            "weekStartDate": next_week['weekStartDate'],
            "weekEndDate": next_week['weekEndDate'],
            "weekNumber": next_week['weekNumber'],
            "year": next_week['year'],
            "categories": {},
            "totalSpentPaise": 0,
            "totalBudgetPaise": 0,
            "overallRiskScore": 0,
            "budgetUtilization": 0,
            "isAutoGenerated": True,
            "aiLastAnalyzed": None,
            "aiSummary": "",
            "adjustmentFlags": {
                "incomeDropDetected": False,
                "incomeSpike": False,
                "festivalMonth": False,
                "emergencySpend": False,
                "cashFluctuation": False,
                "emiDueDate": False
            },
            "transactionSummary": {
                "totalTransactions": 0,
                "incomeTransactions": 0,
                "expenseTransactions": 0,
                "avgTransactionPaise": 0,
                "largestExpensePaise": 0,
                "mostActiveCategory": "food"
            },
            "lastUpdated": datetime.utcnow(),
            "createdAt": datetime.utcnow(),
            "updatedAt": datetime.utcnow()
        }
        
        # Copy maxBudgetPaise from current week, reset all spending to 0
        category_names = ["food", "fuel", "transport", "recharge", "miscellaneous", 
                         "entertainment", "medical", "send_home"]
        
        total_budget = 0
        for category in category_names:
            current_category = current_budget.get('categories', {}).get(category, {})
            max_budget = current_category.get('maxBudgetPaise', 0)
            total_budget += max_budget
            
            new_budget['categories'][category] = {
                "currentSpentPaise": 0,
                "maxBudgetPaise": max_budget,
                "transactionCount": 0,
                "riskScore": 0,
                "status": "safe"
            }
        
        new_budget['totalBudgetPaise'] = total_budget
        
        # Insert into MongoDB
        result = weekly_budgets.insert_one(new_budget)
        
        # Fetch the created document
        created_budget = weekly_budgets.find_one({"_id": result.inserted_id})
        created_budget['_id'] = str(created_budget['_id'])
        
        return {
            "success": True,
            "message": f"Successfully created budget for week {next_week['weekNumber']}, {next_week['year']}",
            "userId": user_id,
            "weekNumber": next_week['weekNumber'],
            "year": next_week['year'],
            "weekStartDate": next_week['weekStartDate'].isoformat(),
            "weekEndDate": next_week['weekEndDate'].isoformat(),
            "totalBudgetPaise": total_budget,
            "insertedId": str(result.inserted_id),
            "createdDocument": created_budget
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": f"Error creating next week's budget: {str(e)}",
            "userId": user_id
        }


if __name__ == "__main__":
    # Test the generator
    import json
    result = create_next_week_budget("usr_rahul_001")
    print(json.dumps(result, indent=2, default=str))
